# Generated by Django 5.1.3 on 2024-12-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0002_rename_user_id_cart_user'),
        ('core_general', '0004_booksitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_general.booksitems'),
        ),
    ]
