# Generated by Django 5.1.3 on 2025-01-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0006_alter_cart_user_id'),
        ('core_general', '0004_booksitems_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_id')},
        ),
    ]
