# Generated by Django 5.1.3 on 2024-12-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core_general.category')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
