# Generated by Django 5.1.3 on 2024-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_general', '0002_booksitems_delete_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksitems',
            name='date',
            field=models.DateField(),
        ),
    ]
