# Generated by Django 5.1.3 on 2024-12-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_general', '0003_alter_booksitems_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksitems',
            name='image',
            field=models.ImageField(default='https://i.pinimg.com/736x/3a/0c/9f/3a0c9f94bc5b671de539935368e75565.jpg', upload_to=''),
        ),
    ]
